pedidon = int(input('Digite um número de 0 á 10 para mostrar a tabuada: '))
print('A tabuada de {} é: ' .format(pedidon))
print('{}x1= {}' .format(pedidon, pedidon*1))
print('{}x2= {}' .format(pedidon, pedidon*2))
print('{}x3= {}' .format(pedidon, pedidon*3))
print('{}x4= {}' .format(pedidon, pedidon*4))
print('{}x5= {}' .format(pedidon, pedidon*5))
print('{}x6= {}' .format(pedidon, pedidon*6))
print('{}x7= {}' .format(pedidon, pedidon*7))
print('{}x8= {}' .format(pedidon, pedidon*8))
print('{}x9= {}'.format(pedidon, pedidon*9))
print('{}x10= {}' .format(pedidon, pedidon*10))